version: '3.0'
 
services:
  mongo:
    image: mongo:4.0.4-xenial
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
 
  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
